name: Deploy to GoDaddy

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set script permissions
      run: chmod +x ./scripts/mscript.sh

    - name: Execute script
      run: ./scripts/mscript.sh
      env:
        TERM: xterm-256color

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to match the Node.js version used in your project

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: |
        CI=false npm run build

    # - name: Zip Build Directory
    #   run: zip -r build.zip build/


    - name: Deploy to GoDaddy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /  

    # - name: Unzip the file on the server
    #   uses: appleboy/ssh-action@master
    #   with:
    #       host: ${{ secrets.SSH_HOST }}
    #       username: ${{ secrets.SSH_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         unzip -o /home/pgf21xbza5eh/public_html/admin.mymink.com.au/build.zip -d /home/pgf21xbza5eh/public_html/admin.mymink.com.au
    #         rm /home/pgf21xbza5eh/public_html/admin.mymink.com.au/build.zip